### PR TITLE
Adding disableWhenInactive flag

### PR DESCRIPTION
**Pull request by sankargorthi**
- [ ] Add test case

### CODE REVIEW

**Comment by sankargorthi** [comment]
Solves #8

**Comment by sean3z** [comment]
This is a great addition and thank you for the PR!
I've replied on #8 but, I'd just like to understand the implications of optionally removing that `disable` call. 

As pointed out, should someone have `disableWhenInactive` set to `false` - this will allow the inactive and keepAlive events to continuously fire after the user is consider inactive. 

Is that the intended functionality?

**Comment by sankargorthi** [comment]
@sean3z I think my problem was that I didn't quite understand how to use "keepAlive" or if it fit my particular [use case](https://github.com/sean3z/angular-activity-monitor/issues/8#issuecomment-239886088).

My usage is something like this:

``` js
link: () => {
  let noteCheckerId;

  ActivityMonitor.options.inactive = 5 * 60; // After 5 minutes of inactivity, stop retrieving the unread note count
  ActivityMonitor.options.disableWhenInactive = false;

  function startCheckingCount() {
     if (!noteCheckerId) {
      checkUnreadCount();
      noteCheckerId = $interval(checkUnreadCount, 1000 * 10);
    }
  }

  function stopCheckingCount() {
    if (noteCheckerId) {
      $interval.cancel(noteCheckerId);
    }
    noteCheckerId = undefined;
  }

  ActivityMonitor.on('inactive', stopCheckingCount);
  ActivityMonitor.on('activity', startCheckingCount);

  function checkUnreadCount() {
    // do some async stuff
  }
}
```

**Comment by sean3z** [comment]
@sankargorthi I think the `keepAlive` event is exactly what you're looking for 😄 
It basically allows you to execute functions at a given interval so long as the user is considered active. Once the user to no longer active, `keepAlive` will no longer execute.

You should be able to accomplish the same using the following:

``` js
link: () => {

  ActivityMonitor.options.inactive = 5 * 60; // After 5 minutes of inactivity, stop retrieving the unread note count
  ActivityMonitor.options.keepAlive = 10; // Execute every 10 seconds

  ActivityMonitor.on('keepAlive', checkUnreadCount);

  function checkUnreadCount() {
    // do some async stuff
  }
}
```

**Comment by sankargorthi** [comment]
Thanks @sean3z - this simplifies my code a great deal! However, the user doesn't automatically get back on to the heartbeat method when they come back from inactivity. I think your code with my change should work perfectly for me.

I'll try my best to add a testcase.

**Comment by sean3z** [comment]
@sankargorthi I think we can close this in lieu of #10, thoughts?

**Comment by sankargorthi** [comment]
Makes sense to me.

**Pull request closed without merging**
